<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../../app/assets/css/reset.css">
  <link rel="stylesheet" href="../../app/assets/css/main.css">
  <title>Home</title>
</head>

<body class="container">
  <header>
    <?php
    require 'header.phtml';
    ?>
  </header>
  <main>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt quibusdam non porro nam amet odio officia voluptas quia delectus maiores dolores eaque beatae distinctio fuga harum, quidem repellendus? Atque blanditiis reprehenderit natus distinctio laboriosam. Doloribus incidunt assumenda velit eligendi tempore ab soluta dolor voluptas recusandae earum, eum accusamus. Temporibus reprehenderit perferendis, dolore officiis ullam ex facere ipsa error ut itaque?</main>
</body>

</html>