<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../../app/assets/css/reset.css">
  <link rel="stylesheet" href="../../app/assets/css/main.css">
  <title>Home</title>
</head>

<body class="container">
  <header>
    <?php
    require 'header.phtml';
    ?>
  </header>
  <main><img src="/app/assets/img/bigBicycle.jpg" alt="bigBicycle"></main>
</body>

</html>