<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../../app/assets/css/reset.css">
  <link rel="stylesheet" href="../../app/assets/css/main.css">
  <title>Home</title>
</head>

<body class="container">
  <header><?php require 'header.phtml'; ?></header>
  <main>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur tempora quo in ea vitae dolorem hic recusandae officia eos eligendi placeat ut cum sapiente ipsa labore, veniam, est aspernatur unde illum cumque inventore laborum, sit nostrum quisquam? Delectus quod quo, ex, ullam eaque architecto ratione impedit sed fugit, explicabo veniam.</main>
</body>

</html>